### PR TITLE
Make the right click to close window option not affect pinned windows

### PR DESCRIPTION
**Pull request by MasonGulu**
## Motivation / Problem

I like to close windows quickly by right clicking on them, but I often close windows I don't intend to close.

## Description

Pinned / "Sticky" windows won't be closed on right click.

## Limitations

The solution works flawlessly, however for people who wish to close pinned windows with a right click this is not currently an optional change.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR touches english.txt or translations? Check the [guidelines](https://github.com/OpenTTD/OpenTTD/blob/master/docs/eints.md)
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by auge8472** [comment]
> … however for people who wish to close pinned windows with a right click this is not currently an optional change.

This change doesn't affect me (because I don't close windows per right click) but in terms of not making mandatory changes to software, that is not exclusively used by one self, because of the own preferences, the changed behaviour should be optional. For other players, who want to close pinned windows with a right click, it must be possible to disable this behaviour (and possibly to reenable it).

**Comment by MasonGulu** [comment]
Then I can look into adding a setting to enable this, if that's a satisfying solution

**Comment by MasonGulu** [comment]
Alright, I've added a setting to toggle this behavior. I hope the variables name are acceptable, but they're a little long. I only included the base strings for `english`. The setting is disabled by default, and enabling it prevents you from closing pinned windows with right click.

**Comment by 2TallTyler** [comment]
Personally I'd suggest changing the existing `Close window on right-click` from a boolean on/off to a dropdown with three options: `Off`, `On`, `On except pinned`, or other wording to mean the same. There's no need to add a totally new setting.

I'd also encourage you to open a PR for this feature in vanilla OpenTTD — I'd be happy to review it there. And if you play JGRPP, it'll most likely propagate downstream from vanilla to JGRPP. 🙂

**Comment by MasonGulu** [comment]
Alright, I've opened a PR in vanilla OpenTTD [here](https://github.com/OpenTTD/OpenTTD/pull/10204), so I'll close this one.

**Pull request closed without merging**
