### PR TITLE
Add AutoGroup Functionality by Lemmy101 <lemmy101@gmail.com>

### PR DESCRIPTION
**Pull request by TrevorCash**
## Motivation / Problem

Adds AutoGroup Buttons By Lemmy101 <lemmy101@gmail.com>

## Description

AutoGroups un-grouped trains.  Helpful for managing large maps

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

I simply applied the lemmy101's patch from here https://www.tt-forums.net/viewtopic.php?t=88795

I'm not very familiar with codebase - but the patch seems to work and I thought I would throw this up here.  

Probably needs translations for other languages etc.

### CODE REVIEW

**Comment by lemmy101** [comment]
Nice cheers for including! Did you see my edit in thread didn't make it into patch never got around to posting it

**Comment by TrevorCash** [comment]
Yeah I added the last edit you made on the forums:

> GetAutoGroupMostRelevantTowns function in group_cmd needs:
> 
> ```
> if (order->GetType() == OT_GOTO_DEPOT)
> continue;
> 
> ```

**Comment by lemmy101** [comment]
Cool!

**Comment by VacuumBreather** [comment]
I had a similar feature in my pack. I'll see if I can add to this once I get the other stuff out of the way

**Comment by VacuumBreather** [comment]
Question: Why do we need a delete autogroup button?

**Comment by VacuumBreather** [comment]
Might also be good to group by cargo

**Comment by TrevorCash** [comment]
I would think that maybe the 2 buttons could be replaced with a single button.  Maybe that single button is a checkbox toggle button.  Where if it is checked on - groups are always maintained automatically.  (Things like order changes would trigger an internal update of the groups).  Each Group could have a flag called autogroup.  When the autogrouper makes the groups this flag is set on.  if the player makes a group the flag is off.  maybe if a autogroup is selected there is a button that appears to convert it into a regular group.  This way you can use the auto grouper to make a rough idea of the grouping you want - and then you can convert groups to your own manual groups and you know they wont be touched.

Beside the sign auto-group button could be a drop-down to choose what to group by:
Route
Cargo

**Comment by VacuumBreather** [comment]
That's a good idea. Grouping by both in a nested fashion would also be great.

Maybe it could be:
- No grouping
- Group by cargo
- Group by Route
- Group by cargo first, route second
- Group by route first, cargo second

**Comment by TrevorCash** [comment]
Yeah that seems like a good breakdown.

**Comment by VacuumBreather** [comment]
Group names will still clash though if they don't get a cargo prefix... hmm

**Comment by James103** [comment]
Is this PR still relevant? I would prefer not having this PR merged due to the aforementioned reasons.

**Pull request closed without merging**
