### PR TITLE
Improved trees

### PR DESCRIPTION
**Pull request by VacuumBreather**
## Motivation / Problem

Prior to this change, trees tended to either cover the entire map like an ancient forest, or alternatively you turn off their growth which breaks industry. Furthermore there are these ugly random tree clumps at the beginning of the game which look like squares on the map someone placed there.

## Description

This change adds a new tree placing setting which removes the ugly random clumps and only slightly modifies the initial placement. The actual growth causes trees to bunch up in higher levels as usual but on the lower 4 levels their growth works differently. The number of trees per tile is limited and the trees spread out over a wider area instead of only to the neighboring tile. That spreads them out more and makes for a nicer look.

This also allows cacti to spread, since they can now use that same algorithm and avoid bunching up, but spread as they should.

example1
example2
example3

Since they now bunch up mostly in mountainous areas and hills, the new hill shading for trees gets even more focus and really makes those highlands visible.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by VacuumBreather** [comment]
Btw, feel free to rename that setting :D I had no other ideas

**Comment by reldred** [comment]
Any thoughts on looking at the tree placement in the arctic treeline patch? It's affected by some heavy banding:
image

I've had a look at it myself but it's way above my skill-grade to try and rectify.

**Comment by VacuumBreather** [comment]
What exactly does that do? I can't really see how that banding happens on that screen? I don't know what the patch does? What's the feature supposed to do?

**Comment by VacuumBreather** [comment]
Hmm, from testing I think you should lover the cost for tunnels again. it builds roads over unnecessarily high peaks now and builds basically no tunnels at all anymore.

**Comment by reldred** [comment]
> 
> 
> What exactly does that do? I can't really see how that banding happens on that screen? I don't know what the patch does? What's the feature supposed to do?
> 
> Also any testing of my tree placement on all the environments and on maps with different height levels is appreciated. Mayve if you push the range of heights (say 1-128, I'm not actually sure what the current max is), then maybe my level checking should be scaled...

Hi, Arctic tree placement patch in Sub Arctic generates temperate trees below the treeline and arctic trees in a configurable height range with the centre of that height range being the snow height. The banding you can see in the screenshot is the clear break between the two types of trees going from the top left corner of the screenshot to the bottom right corner.

I'm personally a big fan of the patch, given I play on maps going up to maxheight 255 (current highest a map can go), some sort of breakup visually of the lowlands from highlands beyond just the snow line (I use a variable snowline with the OpenGFX+ Landscape .grf).

**Comment by VacuumBreather** [comment]
Is that clear break a result of the patch working as currently intended or a bug in the patch?
Also is that patch already integrated in JGR or are you asking for it to become part of this PR?

**Comment by reldred** [comment]
> 
> 
> Is that clear break a result of the patch working as currently intended or a bug in the patch?
> Also is that patch already integrated in JGR or are you asking for it to become part of this PR?
> Also I don't think the snow line is a good idea for this. With some NewGRFs that line can shift. I GUESS you could use the middle between min and max or just the max or something.
> 
> But maybe that should be a separate PR. I don't want to bloat this one for now. But I'll take a look at it when I have the time. I had something like that in my old patch pack.. in that one I even had a heigh beyond which no trees grew at all anymore and you just had bare rocky patches.

Yeah that's already an existing patch.. I always set the lowest point of the newgrf controlled snowline to be the same as the 'map' snow line which the arctic trees patch revolves around. And yes, it does the same thing, above a certain band it stops generating trees. With my previously merged patches to control rock density by height I do the same thing; mountain tops are absolutely barren and rock covered, once the snow recedes from the newgrf controlled snowline the rocks are all exposed.

And no that's fine, I was just bringing it up since it's been something on my mind for a while and you seem to have been reading my mind lately with some of your PR's 😅

**Comment by VacuumBreather** [comment]
Found it. Was an easy fix

image

**Comment by VacuumBreather** [comment]
Never ever use an index based on coordinates or an array position for randomization. That ALWAYS introduces banding and that kind of thing has been the weakness of countless weakpoints in encryption algorithms. Bad bad bad idea.

**Comment by reldred** [comment]
Well there we go, I've just tried it in game and it looks gorgeous!

**Comment by VacuumBreather** [comment]
> Well there we go, I've just tried it in game and it looks gorgeous!

Do you think the sparse trees at lower levels should be scaled? So that range 1-4 tile height is spread out more if the max height is higher than 32?

**Comment by reldred** [comment]
> 
> 
> > Well there we go, I've just tried it in game and it looks gorgeous!
> 
> Do you think the sparse trees at lower levels should be scaled? So that range 1-4 tile height is spread out more if the max height is higher than 32?

I think I would have to see the proposed changes in action and have a play with them knowing what I should be looking for.

> 
> Also I am kinda not happy yet with this artic tree line thing. Sure it generates them correctly but it doesn't prevent the trees from growing beyond the tree line or for you to plant any there. So the trees slowly fill in that sparse area and then creep up the mountain. That needs to be fixed.

Keen to see what you have in mind, arctic tree line has always been one of my favorite patches for aesthetics so any improvements are warmly welcomed.

**Comment by VacuumBreather** [comment]
Ok I modified the area above the snow line and I also extended the lower sparesly grown area around the coast line (tile heights 1-4 up to 1-8 depending on the max height).

Stress test this please with different maps and climates. The lowest (and on artic also the highest) regions should have trees more sparsely and that should STAY that way. So best test it with max tree growth and run the game at fast forward and watch how the trees develop. The icy mountain tops should never get any trees, the snowline trees should remain sparse and the lower levels should also remain sparse, while the mountain sides should be densely forested.

**Comment by reldred** [comment]
1k x 2k x 255maxheight (CptK's Langtal) tropic, only took ten years for the deserts to totally fill with cactus;

image

Not sure if this is what you were going for or not. I personally don't mind dense cactus but I wonder if there's a way to force it only in clumps?

**Comment by VacuumBreather** [comment]
That is NOT what I was going for.

**Comment by VacuumBreather** [comment]
Can you try it again with this change? Did the normal trees on that level in temperate look alright?

**Comment by VacuumBreather** [comment]
Oh yes and obviously turn the tree placement onto "Perfect" It's not the default.

**Pull request merged**
