### PR TITLE
Improve road vehicle pathing near stops

### PR DESCRIPTION
**Pull request by Yourself**
This is actually a re-implementation of a small feature from an existing PR that appears to be dead at this point: https://github.com/JGRennison/OpenTTD-patches/pull/31

The improvement that caught my eye were the pathfinder changes that improved road vehicle behavior near crowded stops. The base behavior tended to result in road vehicles jamming up when turning left into stops since the leading vehicle wouldn't enter the stop quick enough for the trailing vehicle's path to be penalized for going the same way

I've taken the changes from the linked PR and cleaned them up a bit, but it's largely the same algorithm of identifying vehicles ahead of the current one and penalizing their target directions.

### CODE REVIEW

**Comment by JGRennison** [comment]
This has some of the same issues as the code in #31.
Most significantly, it's not valid to use 0xFFFF to mean INVALID_TILE.

The existing pathfinder code only penalises road stops with the occupancy penalty when a vehicle is stopped in them, but this seems to penalise vehicles which are approaching even if they aren't stopping there.

The code as written uses v->tile and v->direction, instead of tile and enterdir from the function parameters. Is that deliberate? It seems like that would give wrong results for cases like custom bridge heads, etc.

I can see some merit in the concept however. I will take a closer look into this soon.

**Comment by Yourself** [comment]
I've fixed the issue with not using INVALID_TILE and also used the tile parameter instead of the combination of v-tile and v-direction since that seems to make sense with respect to the original code.

I think it would be reasonable to adjust the penalties to only apply when other vehicles are stopping at the station, I'll look into making that change this weekend.

**Comment by embeddedt** [comment]
@Yourself Are you still working on this? I'm interested in having less congestion with road stops as well. I'd be willing to see if I can bring this to completion (with credit of course).

**Comment by Yourself** [comment]
@embeddedt I am not currently working on it, you're welcome to take ownership of it.

**Pull request closed without merging**
