### PR TITLE
Updated Galician Extra Strings

### PR DESCRIPTION
**Pull request by pvillaverde**
Hey there! I've just pull the repo in order to update the translations. It's on the new extra file!

### CODE REVIEW

**Comment by James103** [comment]
There are "String name X is used multiple times" errors for the following strings; can you please deduplicate them?
```
STR_NEWS_VEHICLE_AUTORENEW_FAILED
STR_NEWGRF_ERROR_FATAL_POPUP
STR_NEWGRF_ERROR_POPUP
STR_ORDER_TEXT
STR_TIMETABLE_TRAVEL_FOR
STR_TIMETABLE_TRAVEL_FOR_SPEED
STR_TIMETABLE_TRAVEL_FOR_ESTIMATED
STR_TIMETABLE_TRAVEL_FOR_SPEED_ESTIMATED
STR_TIMETABLE_STAY_FOR_ESTIMATED
STR_TIMETABLE_AND_TRAVEL_FOR_ESTIMATED
STR_TIMETABLE_STAY_FOR
STR_TIMETABLE_AND_TRAVEL_FOR
STR_TIMETABLE_TOTAL_TIME
STR_TIMETABLE_TOTAL_TIME_INCOMPLETE
STR_TIMETABLE_STATUS_LATE
STR_TIMETABLE_STATUS_EARLY
STR_CONFIG_SETTING_STATION_RATING_CARGO_CLASS_WAIT_TIME_HELPTEXT
STR_CONFIG_SETTING_DUAL_PANE_TRAIN_PURCHASE_WINDOW_DUAL_BUTTONS_HELPTEXT
```

**Comment by pvillaverde** [comment]
Wops! Checking it, and also checking the other PR I've just made, perhaps it has some error!

**Comment by pvillaverde** [comment]
Okey, They are the first lines, the "override" ones on the english extra language file:
```
##override on
STR_NEWS_VEHICLE_AUTORENEW_FAILED                               :{WHITE}Autorenew failed on {VEHICLE}{}{STRING1}
STR_NEWGRF_ERROR_FATAL_POPUP                                    :{WHITE}The NewGRF "{RAW_STRING}" has returned a fatal error: {}{STRING7}
STR_NEWGRF_ERROR_POPUP                                          :{WHITE}The NewGRF "{RAW_STRING}" has returned an error: {}{STRING7}
STR_ORDER_TEXT                                                  :{STRING6} {STRING4} {STRING}
STR_TIMETABLE_TRAVEL_FOR                                        :Travel for {STRING3}
STR_TIMETABLE_TRAVEL_FOR_SPEED                                  :Travel for {STRING3} with at most {VELOCITY}
STR_TIMETABLE_TRAVEL_FOR_ESTIMATED                              :Travel (for {STRING3}, not timetabled)
STR_TIMETABLE_TRAVEL_FOR_SPEED_ESTIMATED                        :Travel (for {STRING3}, not timetabled) with at most {VELOCITY}
STR_TIMETABLE_STAY_FOR_ESTIMATED                                :(stay for {STRING3}, not timetabled)
STR_TIMETABLE_AND_TRAVEL_FOR_ESTIMATED                          :(travel for {STRING3}, not timetabled)
STR_TIMETABLE_STAY_FOR                                          :and stay for {STRING3}
STR_TIMETABLE_AND_TRAVEL_FOR                                    :and travel for {STRING3}
STR_TIMETABLE_TOTAL_TIME                                        :{BLACK}This timetable will take {STRING3} to complete
STR_TIMETABLE_TOTAL_TIME_INCOMPLETE                             :{BLACK}This timetable will take at least {STRING3} to complete (not all timetabled)
STR_TIMETABLE_STATUS_LATE                                       :{BLACK}This vehicle is currently running {STRING3} late
STR_TIMETABLE_STATUS_EARLY                                      :{BLACK}This vehicle is currently running {STRING3} early
##override off

Adding the override comments I guess it should fix it, I'm gonna think how to handle that on the script in case later on there are more overrides...

**Comment by pvillaverde** [comment]
Well, the overrides doesn't seem to work on other than the english file...
`OpenTTD-patches/src/lang/extra/galician.txt:1: FATAL: Overrides are only allowed in the base translation.`

Maybe I'm not getting the full picture now. Are they needed at all?

**Comment by JGRennison** [comment]
> Well, the overrides doesn't seem to work on other than the english file... `OpenTTD-patches/src/lang/extra/galician.txt:1: FATAL: Overrides are only allowed in the base translation.`
> 
> Maybe I'm not getting the full picture now. Are they needed at all?

You don't need to translate those strings again.
They are already in the src/lang/galician.txt from upstream.

**Comment by JGRennison** [comment]
The purpose of the overrides is primarily to change the parameter counts of the {STRINGN} codes.

The main motivation behind doing it this way is so that the main language file can be (almost entirely) unchanged from upstream, reducing the number of merge conflicts with upstream changes, as these were previously rather frequent.

Translations of the upstream language strings are probably better off being done through the vanilla eints service.

**Comment by pvillaverde** [comment]
Totally agree with the purpose, thanks for the explanation! I've just removed that lines, should be good now!

**Comment by JGRennison** [comment]
Thanks, this is merged now

**Pull request closed without merging**
