### PR TITLE
Translate de; improved breakdowns, adjacent level crossings

### PR DESCRIPTION
**Pull request by auge8472**
New translations for improved breakdowns and for adjacent level crossings.

**Attention**: I wasn't able to include the [first commit of adjacent-level-crossings-translation](https://github.com/auge8472/OpenTTD-patches/commit/063c125f20213c03b18f17bf12a297c184555195) into this pull request. I don't know what's wrong.

### CODE REVIEW

**Comment by JGRennison** [comment]
The first commit had been merged already, which is why it couldn't be added to a pull request.

Thanks for the patches.

**Comment by auge8472** [comment]
Ah ja, then it's done. :-)

**Comment by auge8472** [comment]
I have to add a note.

The adjacent-level-crossing-commit from today is a fix for a wrong placeholder string. Compiling the 0.8 with my november 8th commit (the one you merged before) will fail.

**Comment by JGRennison** [comment]
I noticed that one when compiling so put a fix in here https://github.com/JGRennison/OpenTTD-patches/commit/6939bc7d87b7da12d1beecd504b99c37f9ea054d

**Pull request merged**
