### PR TITLE
Update: Korean translation up to 5615cee

### PR DESCRIPTION
**Pull request by telk5093**
Merge this just before new release.
Please let me know if additional extra string is added

### CODE REVIEW

**Comment by telk5093** [comment]
Thanks for letting me know :)

**Comment by JGRennison** [comment]
2a5a9c2f9de88c1a23123391b1b05e9a4c905589 is another

**Comment by telk5093** [comment]
Yeap added XD

**Comment by JGRennison** [comment]
d3fbe88a9c849ba813430da136f9118ea1ff26e5 and ccdca8ae527d5b41873053fa477c90e9ab4d91d0 are probably the last ones

**Comment by telk5093** [comment]
Always thanks for noticing me <3

**Comment by JGRennison** [comment]
Thanks for this :)

**Pull request merged**
