### PR TITLE
Fix: overflow in CloneVehicleName

### PR DESCRIPTION
**Pull request by Yourself**
When cloning a vehicle with a sufficiently large integer at the end of its name, the incrementing algorithm would overflow and insert a negative number into the new vehicle name. This was due to an attempt to parse the number into a signed `long` type.

This PR fixes this issue by avoiding parsing the integer altogether and simply incrementing it in-place in the string. Performance should be unaffected as the new algorithm works in place and only needs to reallocate when the number of digits grows. Compared to the previous algorithm which utilized string streams for parsing and formatting, this change may even be an improvement.

Some issues remain unaddressed, such as the requirement that the number be the very last part of the name. Any non-digit characters after a number will cause it to append a new number rather than increment an existing one. This behavior is unchanged. Likewise digit group separators are not handled, so the string "1,999" gets incremented to "1,1000".

### CODE REVIEW

**Comment by larryfenn** [comment]
A picture of the old, broken behavior - as a joke someone made a vehicle ending in 91391... and on cloning it wrapped around:
Untitled

**Comment by Yourself** [comment]
It's unclear to me why the regression test is failing here as the failure seems unrelated to the change I made. It's testing a number of RNG features which are coming out different somehow.

**Comment by Yourself** [comment]
I just tested against the main jgrpp branch and the regression test fails there as well in the same way.

**Comment by James103** [comment]
It's because of a combination of the increased max loan size breaking the financial-related lines plus different RNG behavior breaking the RNG-related calls (including `GetPresidentName()` as company president is randomly decided at start of game)

**Comment by JGRennison** [comment]
I tend to ignore the regression tests, as whether they pass or not does not really tell you anything useful, so I hadn't noticed that they don't currently pass. I will see to that separately.

I'm happy to proceed with this fix, thanks for the contribution.

**Pull request merged**
