### PR TITLE
Vehicles waiting

### PR DESCRIPTION
**Pull request by JeroenDStout**
Putting up front I hope you are OK with pull requests!

This is an experimental change to the functionality for vehicles leaving stations. They will check their next station immediately, and if it is identical, they will not actually leave the station. This is great for conditional orders where vehicles start circling stations and blocking infrastructure. I actually made this because the alternative was tearing my hair out.

VS really didn't do well with this patch and I had to modify some code; and I am not that well-versed in OpenTTD's code, so any serious implementation may be better as a rewrite rather than this actual PR.

go

wait

Things that still go wrong:
* Vehicles at the station can block indefinitely if they never get to an order to leave (until they need servicing)
* Vehicles will still show exhaust fumes

Despite these problems I figure this is more 'intended behaviour' than the current behaviour.

### CODE REVIEW

**Comment by JeroenDStout** [comment]
I also just added a fix. Vehicles were not refitting properly at stations. It seems sometimes their 'current cargo' did not correspond to the actual cargo they carry (possibly because of multi-part vehicles). I simply removed the check.

**Comment by JeroenDStout** [comment]
I added a change to the road pathfinding in yapf.

There was an issue where vehicles would decide which station to go to *before* it was registered the vehicle directly in front of them was going there. This would make them follow the preceding vehicle, and run into a block. These changes check the directions of vehicles in front of the current pathfinding vehicle and penalise the vehicle for going to those tiles, plus extra if that tile is a loading area. This also helps clear dual lane roads, as jammed vehicles will prefer to use a secondary road if they have vehicles in front of them.

divest

**Comment by JGRennison** [comment]
Thanks for the contributions.

These changes look interesting and make sense in principle, it may take me
some time to examine them in detail.
Removing assertions in the btree code is alarming and I would advise
against that.
In general weakening assertions without a clear rationale is dangerous
because it can lead to regressions and invariant/consistency bugs slipping
through.

The road pathfinding and changed order behavior seem somewhat separate
issues. It may be worth tackling them separately.

**Comment by JeroenDStout** [comment]
@JGRennison Yeah, it was definitely not my intention to have the disabling of assertions as an intended change, I just could not find a way to get the code to compile properly without that. So just pretend I did not do that.

But yes, I am OK with taking this in any direction you want. They are both relatively smaller changes, but I also do not immediately intend to make a patch for the thing as a whole.

**Comment by JGRennison** [comment]
A few more comments:
Using 0xFFFF as a sentinel constant for an invalid tile isn't a good idea as this is a valid tile index on large maps. INVALID_TILE should be used instead.
The pathfinder penalty for a predicted occupied road vehicle target looks to be road_curve_penalty * 3 + road_stop_occupied_penalty * 2. Why add the curve penalty as well?
It's unclear whether the intended change to the penalties for currently occupied road stops are to double or halve them?
I am pondering if a more general check than for vehicles on the next tile would be better, however that might be overkill if just using the next tile is good enough.
I'm also wondering if the vehicle leaving station change could cause regressions. The OpenTTDCoop people (and me) sometimes use creative order constructs which could be impacted by this. It may be useful to add a way/setting to enable the old behaviour.

I've updated the project files in the jgrpp branch. As I don't use/need them I sometimes forget to update them.

**Comment by DasTestament** [comment]
This PR is dead?

**Comment by JGRennison** [comment]
Superseded by #138

**Pull request closed without merging**
