### PR TITLE
Forward-port the proposed changes to GUI code in master

### PR DESCRIPTION
**Pull request by techgeeknz**
This branch aims to forward-port the changes proposed in https://github.com/OpenTTD/OpenTTD/pull/8217 back to JGRPP

### CODE REVIEW

**Comment by James103** [comment]
Before each JGRPP release, JGR rebases JGRPP onto the latest master at the time of the release. If the next release happens after OpenTTD/OpenTTD#8217 is merged, then the rebase will already include the changes present there. Does that make this PR not needed (in the long term), or is there some other reason for this PR that applies even if OpenTTD/OpenTTD#8217 is merged?

**Comment by JGRennison** [comment]
I periodically merge the upstream master into my own branch, but this does not strictly have to happen before each release.
At present that merge is likely to be delayed due to the cmake changes.

If OpenTTD/OpenTTD#8217 is merged upstream, it will later be merged into this branch.

**Comment by techgeeknz** [comment]
The JGRPP codebase is more complex than upstream, and so there are other places in the code that will need to be fixed if my changes go ahead. This is a courtesy to aid in merging now or later on; feel free to cherry-pick what you need.

If it will help, I can have a crack at merging the build system changes for you; I could potentially learn a lot from doing that.

**Comment by JGRennison** [comment]
> If it will help, I can have a crack at merging the build system changes for you; I could potentially learn a lot from doing that.

Feel free to have a go. :)
I'd expect that MinGW and some of the debugging stuff will be the most trouble. MinGW is quite a faff to get set up under the old configure system as well.

**Comment by techgeeknz** [comment]
> Feel free to have a go. :)
> I'd expect that MinGW and some of the debugging stuff will be the most trouble. MinGW is quite a faff to get set up under the old configure system as well.

I don't have access to Windows to test the MinGW stuff; is there anything specific to JGRPP that you would expect to cause trouble there?

**Comment by embeddedt** [comment]
@techgeeknz MinGW can also be used as a cross-compiler; I use this to build Windows executables for my fork. The [instructions for doing so](https://wiki.openttd.org/Cross-compiling_for_Windows#Compiling_manually_with_MinGW) are on the OpenTTD wiki.

**Comment by techgeeknz** [comment]
> @techgeeknz MinGW can also be used as a cross-compiler; I use this to build Windows executables for my fork. The [instructions for doing so](https://wiki.openttd.org/Cross-compiling_for_Windows#Compiling_manually_with_MinGW) are on the OpenTTD wiki.

Thanks for that. I can look into it once I get cmake to work with JGRPP on GCC.

**Comment by techgeeknz** [comment]
Out of this lot, the only ones that are likely to be generally useful are https://github.com/JGRennison/OpenTTD-patches/pull/161/commits/49f8101e43b9890be89645d45515ec2ee9d2180f and, possibly, https://github.com/JGRennison/OpenTTD-patches/pull/161/commits/295f2f6a6699e906b0ab812b4b34aec55c3470fa. I imagine all of the others will merge across cleanly if and when they land in master.
https://github.com/JGRennison/OpenTTD-patches/pull/161/commits/6a14b68517a72174c32abb2bbf48cee59ac09c46 is probably also useful right now, to avoid visual confusion between `AddDirtyBlock` and `AddDirtyBlocks`.

**Comment by James103** [comment]
@techgeeknz This PR was last updated over 6 months ago. Is it still relevant?

**Comment by techgeeknz** [comment]
> @techgeeknz This PR was last updated over 6 months ago. Is it still relevant?

Probably not; I haven't had time to work on it since starting a new job 😥

**Comment by unbeatable-101** [comment]
Should this be closed? Both of the PRs in the upstream repo were.

**Comment by JGRennison** [comment]
Yes, that's probably prudent. It can be reopened again later if needed.

**Pull request closed without merging**
