### PR TITLE
Allows configuring the width of the coast in tropic maps

### PR DESCRIPTION
**Pull request by reldred**
Allows configuring the width of the coast in tropic maps that generates as tropiczone_normal before the desert kicks in, it does this by creating two additional arrays which house the coordinates to create a filled circle of radius of 19 tiles, and 25 tiles. the default creates a radius of 13 tiles.

I'd eventually like to add an Extra Large setting but manually creating the array of coordinates is horrible.

I wedged this setting in beside the setting for tropic width around rivers despite it not fitting into the rivers/lakes category because it still feels the most relevant place for now.

### CODE REVIEW

**Comment by JGRennison** [comment]
Automatically generating the coordinate array ought to be possible, given that it's just a circle.
The slightly strange ordering of the original array suggests that there must be something more going on though.
If I get some time I will take a look later. I'd be fine with going ahead with it as it stands now though.

**Comment by reldred** [comment]
> 

The impression I got looking at it was that the array was extended by hand at some point. There doesn't appear to be any rhyme or reason to it otherwise. I hand crafted the first two arrays, the 3rd that I just added for the extra large setting I cheated and used a tool that generated svg's of filled circles for some minecraft thing, extracted the svg coords and then mangled them in excel to get raw coords.

Doesn't appear to be any appreciable speed impact.

Autogenerating the array would be cool, but it also sounds like maths and algorithms and we both know I can't do those.

**Comment by reldred** [comment]
also crap I missed your changes when I sat down this morning to make more tweaks, I'll try and merge it all and do another push

**Comment by reldred** [comment]
right, barring adding voodoo magic to autogen the arrays, I'm happy with this one now. I've fixed the mess I made of your de-duplication code.

also, the strings now state how large the diameter of the search circles are which matches the existing river settings.

**Comment by JGRennison** [comment]
I've changed the array format to make it a bit more compact/manageable.

I'm not sure about putting the search diameters in the setting value strings.
The actual width of the tropic zone that is generated is half of the search diameter, it seems a bit misleading.

For rivers/lakes it's a bit more plausible that the width refers to the sum of the zones on both sides.

**Comment by reldred** [comment]
> I've changed the array format to make it a bit more compact/manageable.
> 

Marvelous. That's a lot easier to manage if additional settings are required.

> I'm not sure about putting the search diameters in the setting value strings. The actual width of the tropic zone that is generated is half of the search diameter, it seems a bit misleading.
> 
> For rivers/lakes it's a bit more plausible that the width refers to the sum of the zones on both sides.

I mean this is still kinda the same with Coasts, a single tile of water in a desert will behave the same as the river/lake example.

I do agree this looks cleaner without however,

**Pull request merged**
