### PR TITLE
change the tree line width for arctic tree line patch from 20 to 64

### PR DESCRIPTION
**Pull request by reldred**
Just a short sharp one. I found when playing with maxheight 255 on arctic maps (especially all the stress testing of public roads) that I was finding the arctic tree line range of 20max to be a little lacking.

This PR simply changes settings.ini to allow for a max range of 64. Initially I wanted to modify tree_cmd to allow configuring an additional height range above but that got too complicated for my puny brain too quickly. On a 2k x 4k map with maxheight 255 and snow height set to 48 I've found this produces quite nice results.

### CODE REVIEW

**Comment by VacuumBreather** [comment]
I'm not sure this will work. The treeline range is used in a lookup of an array that's only 24 long. Right now 24 is the maximum unless the algorithm is changed

**Comment by reldred** [comment]
It's not too bad, works relatively well. Snow line height is set to 48, range is set to 64. Getting trees as high as 70 and as low as 25. Only an effective range of 45 in this instance so there's definitely diminishing returns.

image
image

**Comment by VacuumBreather** [comment]
I know it can WORK but probably because of an array overrun

**Comment by JGRennison** [comment]
It doesn't overrun the array, the distribution just gets truncated.
The array is sized at 24 which is consistent with an effective range of about 48.

Setting the array size to 78 is enough for a full distribution at 64, giving an effective range of about 156.
Is it really useful to have the upper limit that high though?

**Comment by VacuumBreather** [comment]
Just FYI. My tree code checks tree distance from snowline and assumes the trees stop at snowline+range.

**Comment by reldred** [comment]
> 
> 
> It doesn't overrun the array, the distribution just gets truncated.
> The array is sized at 24 which is consistent with an effective range of about 48.
> 
> Setting the array size to 78 is enough for a full distribution at 64, giving an effective range of about 156.
> Is it really useful to have the upper limit that high though?

I was only trying to achieve a range of around 64, getting 45/48 was a 'good enough' case. The default range of 20 was fine on maps with maxheight 127 or lower, but I found it lacking for maxheight 255 on good heightmaps.

**Comment by reldred** [comment]
> 
> 
> Just FYI. My tree code checks tree distance from snowline and assumes the trees stop at snowline+range.

Saw the same behavior with Perfect tree gen, snow height 48, arctic tree line width 64; effective range of 45 with growth between z level 70 and 25. So it definitely is the lower bounds below the snowline that are being truncated in both improved and perfect tree gen, I'm trying original now but I'm not expecting much difference, I've been playing around with this modification for a little while now before one of the previous jgrpp releases.

**Comment by JGRennison** [comment]
The truncation issue should be resolved now. I've also rebased this so that it includes the other tree PR already merged for testing.

**Pull request merged**
