### PR TITLE
Advanced train purchase window

### PR DESCRIPTION
**Pull request by VacuumBreather**
## Motivation / Problem

When buying a train it is advantageous to be able to view, sort, and filter engines and wagons separately. Especially when using large or multiple train sets.

## Description

This new train purchase window has two colums. One for locomotives and power cars, one for wagons.

## Limitations

There were multiple changes and updates to the code of the original purchase window since I added this one, so there are a few things not matching up. I fixed and updated what I could see at first glance but there's still a few issues so I'd appreciate some help with this. It's a worthy addition I think when we get it running again. And it shouldn't be hard to do. The code is mainly intact, it's just small API updates and changes from pointers to references or C to C++ types that are the issue.

## Checklist for review

Some things are not automated, and forgotten often. This list is a reminder for the reviewers.
* The bug fix is important enough to be backported? (label: 'backport requested')
* This PR affects the save game format? (label 'savegame upgrade')
* This PR affects the GS/AI API? (label 'needs review: Script API')
    * ai_changelog.hpp, gs_changelog.hpp need updating.
    * The compatibility wrappers (compat_*.nut) need updating.
* This PR affects the NewGRF API? (label 'needs review: NewGRF')
    * newgrf_debug_data.h may need updating.
    * [PR must be added to API tracker](https://wiki.openttd.org/en/Development/NewGRF/Specification%20Status)

### CODE REVIEW

**Comment by James103** [comment]
I remember this being in Joker's Patch Pack before. See [this video](https://youtu.be/1VUrn4UnSM0?t=1658) for what it looked like back then.

**Comment by VacuumBreather** [comment]
> I remember this being in Joker's Patch Pack before. Did you take inspiration from Joker's Patch Pack for this feature?

Since I am Lt_Joker, you could say that

**Comment by VacuumBreather** [comment]
Ok this should be good to go

**Comment by VacuumBreather** [comment]
Sorry for that messy build_vehicle_gui.cpp diff. This diff viewer is so retarded.
"Oh I recognize two curly braces.. nothing inside matches... must tbe the same function..." sigh

**Comment by James103** [comment]
I was able to reproduce the following issues after applying the changes from this patch (included in jgrpp-0.42.0):
* #296 
* #297

**Comment by andythenorth** [comment]
Adding a screenshot of this, as I think it's a valid candidate for vanilla, but a picture will tell a thousand words etc

image

**Comment by auge8472** [comment]
Unlike @andythenorth, I am not convinced by the new purchase window. First, the vehicle list gets cluttered anyway (especially with huge sets like Andy's Iron Horse ;-)) even with two columns but yes, it would be nice to be able to distinguish locomotives and wagons in a first sight. I think, the two column list is an advantage for this purpose, not because of *uncluttered* lists but because of visually separating wagons from the locomotives. A "yes" from me up to this point.

But second, and that's much more relevant for *me*, the UI is IMHO broken. I got trapped *several times* by selecting wagons for my new train but clicking the buy-button of the locomotive column (that I used directly before to buy the locomotive) instead the one of the wagon-column. Because of that I had to move back to the classic single column purchase window. This trap would be preventable …

1. … if there was only one set of buttons for both columns and …
2. … if the focus would switch between the columns with the mouse clicks inside the lists

 *For me* the advanced purchase window is difficult to use in its current state. IMHO it needs further polishing to adopt it into the vanilla game.

**Pull request merged**
