### PR TITLE
Korean: Add Chunnel translations and etc.

### PR DESCRIPTION
**Pull request by telk5093**
* Add translations about the chunnels
 * Fix some strings

### CODE REVIEW

**Comment by JGRennison** [comment]
Hello, thanks for contributing these translations.
Unfortunately, these conflict with the translation changes which you also committed to trunk in r27847.
Would you be able to update your pull request to resolve that?

**Comment by telk5093** [comment]
Do you mean the origin strings of stable version? (as can see here?: http://git.openttd.org/?p=trunk.git;a=commitdiff;h=3b6fa4e33fa6d74e9b8e96d537effb612c9cef89 )

**Comment by telk5093** [comment]
Done. Is it okay?
(One conflict is remained, but just ignore that if you can.)

**Comment by JGRennison** [comment]
Thanks for the updates, I've merged these into a single commit and applied it.

**Pull request closed without merging**
