### PR TITLE
No slowdown in curvy roads

### PR DESCRIPTION
**Pull request by VacuumBreather**
Prior to this change, road vehicles would always slowdown in curves. This forces the player to build grid like roads. With new height levels and more mountainous maps and in the absense of diagonal roads this causes unnecessary pain. There should be an option to turn this off, so mountainous maps and curvy roads are not punishing the player unnecessarily. Nobody wants to build grid like roads outside of towns.

### CODE REVIEW

**Comment by JGRennison** [comment]
I'm a bit surprised that cornering slowdowns are considered sufficiently bad that it is necessary to build on a grid. It's not something I worry about when building roads.
Still, I've got no objections. If you don't mind I will cherry-pick as I don't think the two extra merges are needed.

**Comment by VacuumBreather** [comment]
I measured it once and the vehicles arrive significantly later and cause a big profit loss when there's a lot of curves. Up to the point that a route was no longer sustainable.

**Comment by JGRennison** [comment]
Cherry-picked into: ec40677fdc350823967fd1a2cbb048c38d9a4697

**Comment by James103** [comment]
> I don't think the two extra merges are needed.

@VacuumBreather Why exactly did you include those extra merges? Could they be removed from this and/or future PRs to the main jgrpp branch? If not, why not?

**Comment by VacuumBreather** [comment]
Extra merges? I just pulled back the current state of the repository with a reverse pull request

**Pull request closed without merging**
