### PR TITLE
Various departure boards UI/UX bugfixes/improvements

### PR DESCRIPTION
**Pull request by cake-pie**
### Bug: "Show via" widget not redrawn when state is changed as a side effect

The "Show via" widget gets enabled/disabled as a side effect of "Show departures" being toggled, but it was not being marked dirty for redrawing, leading to some strange behavior.

### Refactor widget raised/lowered toggling

`LowerWidget` and `RaiseWidget` both simply wrap `SetWidgetLoweredState`, so we can eliminate conditional test and nested call by passing the boolean directly to the latter. Code readability unaffected.
 
### Bug: "Show ships" and "Show aircraft" widget tooltips reversed

The ordering of strings did not match the ordering of widget enum. Could be fixed by switching the ordering, but instead prefer to ...(see next)

### Enhancement: dedicated tooltip text for "Show &lt;vehicle type&gt;" widgets

Add dedicated tooltip text for these four widgets, `STR_DEPARTURES_SHOW_*_TOOLTIP`, instead of repurposing `STR_STATION_VIEW_SCHEDULED_*_TOOLTIP` which are for a different window (see `station_gui.cpp`). This lets us change the wording to something more accurate and appropriate to this context. For instance, number of entries on departure board is capped (default: 10) so more accurate to refer to "upcoming" arriving/departing vehicles rather than "all" vehicles; same vehicle may show multiple times on the departure board; etc. Meaning of the text may be even more inaccurate for translations in other languages.

Also renamed `STR_STATION_VIEW_SCHEDULED_TOOLTIP_CTRL_SUFFIX` to `STR_DEPARTURES_SHOW_TYPE_TOOLTIP_CTRL_SUFFIX` accordingly; as far as I can tell it is only used in departure boards and not station view.

### Bug: stuck with empty list if `departure_show_both` setting switched on while "Show departures" is off on existing window

If you have a departure board already open and set to show only arrivals and not departures, going to settings and turning `departure_show_both` on leaves you with an empty listing. Since this also disables the "Show arrivals" and "Show departures" widgets, you are forced to go back and ensure "Show departures" is turned on before changing the config setting.

### Enhancement: more intuitive "Show arrivals" and "Show departures" widget lowered state while disabled

Related to the previous, when `departure_show_both` setting is on, besides disabling "Show arrivals" and "Show departures" widgets, also force them to be in the lowered state. This is a more intuitive reflection of the behavior experienced by the end user -- both are being shown -- even though internally the implementation subtleties are somewhat different (put arrival times in departure entries; don't show arrivals independently).

### CODE REVIEW

**Comment by cake-pie** [comment]
Another change I was considering is to update the config settings strings related to departure boards to better reflect that either arrivals, departures, or both can be displayed, and not just departures. Basically, use neutral wording where possible, e.g. "maximum number of _entries_ to show", or substitute "arrivals/departures" for "departures". Maybe even rename "Departure boards" group heading to "Travel information display".

Just wanted to check if these changes are actually desired before expending effort on them.

https://github.com/JGRennison/OpenTTD-patches/blob/822c29e6c231fe6e9d09f24b3ad7c3b2e23f554d/src/lang/english.txt#L4730-L4745

**Comment by JGRennison** [comment]
Thanks for your work on this. These changes all look good.

On the 'stuck with empty list if departure_show_both switch on' issue, the same issue also occurs if both arrivals and departures are switched off before switching departure_show_both on. This seems very unlikely to occur with normal usage but might be worth fixing at the same time?

I'm happy for you to go ahead and reword setting strings as well, if you like.
I'd suggest leaving the section title the same though, as that is what the feature has come to be known as, and some users will be unable to find or recognise it if it's not named as expected.

**Comment by cake-pie** [comment]
Fixed a minor oversight on my part in the constructor, `departure_show_both` should not apply to waypoints.

> the same issue also occurs if both arrivals and departures are switched off

Poor wording on my part earlier, bug is due to departures being switched off, whether arrivals was on or off is irrelevant. Hence the fix does already cover the other case you described.

> reword setting strings

Also done. Left the section heading / feature name as it is.

All set!

**Comment by JGRennison** [comment]
Thanks, this is merged now.

**Pull request merged**
