### PR TITLE
Update: Simplified Chinese translations

### PR DESCRIPTION
**Pull request by WenSimEHRP**
Fixed many errors, and rephrased many strings.

### CODE REVIEW

**Comment by WenSimEHRP** [comment]
Git again thinking the whole file is changed due to CRLF line ending. I'll fix that in the next force push.

**Comment by WenSimEHRP** [comment]
Ready now

**Review by WenSimEHRP — COMMENTED** [review]
PR is ready now :-)

**Comment by JGRennison** [comment]
Thanks :)

**Pull request merged**
