### PR TITLE
Merge OpenTTD/master and configure CMake build system

### PR DESCRIPTION
**Pull request by techgeeknz**
This is the first iteration. It builds under GCC on Linux, but there is still work to do. Specifically, there are changes to the `Makefile*.in`, `config.lib`, `configure`, `findversion.sh`, and `projects/generate` files which may need to find new homes under the new build system. The last upstream commit to include these files is eeed3a7613d375f66781f53b42e03729a4ca1c33.

To simplify the merge, I reverted some of the recent commits to `master`. These are in https://github.com/techgeeknz/OpenTTD-patches/tree/jgrpp_master_cmake

### CODE REVIEW

**Comment by JGRennison** [comment]
Thanks for this. I've added a temporary branch [pr-163](https://github.com/JGRennison/OpenTTD-patches/commits/pr-163) to this repo with this in.
I've started to add some of the missing stuff previously in configure.

**Comment by techgeeknz** [comment]
Cheers. Please let me know if there's any other way I can help with this.

**Comment by JGRennison** [comment]
I've rebased and merged this now. Many thanks.

**Comment by techgeeknz** [comment]
Thanks. I'm not quite sure what happened to this pull request. My aim was to reset it to follow https://github.com/JGRennison/OpenTTD-patches/tree/pr-163 and then try merging in more commits; but that seems quite redundant now :wink:.

**Comment by embeddedt** [comment]
@techgeeknz My apologies if I'm asking in the wrong place, but I haven't figured out how to get MinGW cross compiling on Linux. These are the steps I used to use (from the [wiki](https://wiki.openttd.org/Cross-compiling_for_Windows#Compiling_manually_with_MinGW)):

```
# notice that OpenTTD can't accept PKG_CONFIG_LIBDIR as an option
env PKG_CONFIG_LIBDIR=/usr/local/i686-w64-mingw32/lib/pkgconfig \
    ./configure \
    --host=i686-w64-mingw32 \
    --prefix=/usr/local/i686-w64-mingw32 \
    --enable-static --static-icu \
    --with-lzo2=/usr/local/i686-w64-mingw32/lib/liblzo2.a \
    CFLAGS="-I/usr/local/i686-w64-mingw32/include" \
    LDFLAGS="-L/usr/local/i686-w64-mingw32/lib"
make
```

Unfortunately, I think CMake has its own package detection method and I don't think the user has as much control. Do you know what the equivalent CMake options are?

**Comment by techgeeknz** [comment]
I think upstream recently got cross-compiling working on CMake; we probably need to ask there and maybe merge a few more commits to make it work.

**Comment by JGRennison** [comment]
You'll need a CMakeToolchain file for your compiler. My 32 bit MinGW one (ripped form StackOverflow) looks like:
```
# the name of the target operating system
SET(CMAKE_SYSTEM_NAME Windows)

# for 32 or 64 bits mingw-w64
# see http://mingw-w64.sourceforge.net/
set(COMPILER_PREFIX "i686-w64-mingw32")
#set(COMPILER_PREFIX "x86_64-w64-mingw32")

# which compilers to use for C and C++
find_program(CMAKE_RC_COMPILER NAMES ${COMPILER_PREFIX}-windres)
#SET(CMAKE_RC_COMPILER ${COMPILER_PREFIX}-windres)
find_program(CMAKE_C_COMPILER NAMES ${COMPILER_PREFIX}-gcc)
#SET(CMAKE_C_COMPILER ${COMPILER_PREFIX}-gcc)
find_program(CMAKE_CXX_COMPILER NAMES ${COMPILER_PREFIX}-g++)
#SET(CMAKE_CXX_COMPILER ${COMPILER_PREFIX}-g++)


# here is the target environment located
SET(USER_ROOT_PATH /home/jgr/mingw32/)
SET(CMAKE_FIND_ROOT_PATH  /usr/${COMPILER_PREFIX} ${USER_ROOT_PATH})

# adjust the default behaviour of the FIND_XXX() commands:
# search headers and libraries in the target environment, search
# programs in the host environment
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```

The associated cmake command which I use is:
```
CFLAGS="-I/home/jgr/mingw32/include" CXXFLAGS="-I/home/jgr/mingw32/include" LDFLAGS="-L/home/jgr/mingw32/lib" cmake -DCMAKE_TOOLCHAIN_FILE=Toolchain-mingw32.cmake ..
```

You'll probably need to change paths/names/etc.

**Comment by embeddedt** [comment]
Thanks @JGRennison; that's exactly what I was looking for.

**Pull request closed without merging**
