### PR TITLE
Add: new town council "indifferent" attitude

### PR DESCRIPTION
**Pull request by Yourself**

### CODE REVIEW

**Comment by telk5093** [comment]
I think it is not a good idea to translate all languages via translators.
(In my case, korean, ``무관심한`` is quite awkward. It should be ``무관심``)

**Comment by James103** [comment]
@Yourself How did you translate the word "Indifferent" to 50+ different languages? Most likely, you used Google Translate.

**Comment by JGRennison** [comment]
This changes the existing setting values and so breaks existing savegames and config files.
A previously unused value should be used instead. If possible this shouldn't clash with likely future changes from trunk.
Either end of the range can be extended and/or the drop-down can be visually re-ordered if necessary.

**Comment by Yourself** [comment]
@JGRennison I don't think I can extend it in the negative direction since the underlying setting is unsinged and I'm not sure what impact that would have. I could extend it to the other end but I don't know how to force a different drop-down box order here since this seems to be controlled through settings.ini and I'm not familiar with what options that provides to change the order of elements (as far as I knew they could only be displayed in the order they appear in the language files).

**Comment by Yourself** [comment]
> @Yourself How did you translate the word "Indifferent" to 50+ different languages? Most likely, you used Google Translate.

Yes, I did, I created a script that allows me to insert new entries into the language files and will automatically translate for each language through my own Google Cloud account. Generally I don't expect it to do a stellar job, but I figure it's better than nothing. I at least double check the Japanese and Chinese translations.

@JGRennison I've found *a* way to leave the underlying numerical value undisturbed while presenting the settings in a reasonable order in the drop-down box, but I'm unsure if what I did was the best way to approach this.

**Comment by James103** [comment]
Is this pull request still relevant? I would still like something like this to be added to the patch pack (or even better, trunk) as per the following in https://github.com/OpenTTD/OpenTTD/pull/8461#issuecomment-757173760:
> As an aside, a large fraction of players already find town authorities quite constricting, and are quite happy to demolish rivers, towns, mountains, etc. to fit perfectly flat and straight mainlines. I think that such a change would not be well appreciated by such players.

**Comment by embeddedt** [comment]
@James103 If this patch is completely disabling the local authority, then the [Eternal Love](https://bananas.openttd.org/package/game-script/6a667330) script might already be accomplishing this.

**Comment by JGRennison** [comment]
I've merged this with some minor adjustments.

**Pull request closed without merging**
