### PR TITLE
Fixed Simplified Chinese translation

### PR DESCRIPTION
**Pull request by WenSimEHRP**
## Description

fixed SC translation.

### CODE REVIEW

**Comment by JGRennison** [comment]
There were some issues with string codes, could you check that it still all looks OK?

**Comment by WenSimEHRP** [comment]
Sure, however I cannot build the program, so, can you give me some further information please?(like screenshots) So I can find out which string is wrong.

**Comment by WenSimEHRP** [comment]
I'll check it when I have time.

**Comment by JGRennison** [comment]
I fixed the issues which stopped it from building.
Mostly these were plural suffixes which were left in, e.g. `{P "" s}` which I gather Chinese does not use.
So I think it should be fine as is. Thanks for the contribution.

**Pull request merged**
